#!/bin/bash
# minionctl {create, start, status, restart, stop}

SUBCOMMAND=$1
OPTERR=1
echo $subcommand
shift 1

case "${SUBCOMMAND}"
in 
	create) while getopts m:i:a:v:h option "$@";
		do	
			case $option
			in
			m)  MPORT=${OPTARG};;
			i)  IPSEC_ADAPTER=${OPTARG};;
			a)  REMOTE_IPSEC_ADDR=${OPTARG};;
			v)  MPORT_ID=${OPTARG};;
			h|*)  echo "Syntax: create -m minion-port-name -i ipsec-adapter-name -a remote-ipsec-address -v VXLAN-id" ;;
			esac
		done
		./minion_create $*
		;;
	start)       ;;
	status) ./minion_status;;
	restart) ;;
        stop) ./minion_delete;;
	delete) ./minion_delete;;
esac



while getopts cmd option
do
	case "{$option}" in
	help) echo "Syntax....";;
 	create) ;;
	start) ;;
	status) ;;
	restart) ;;
	stop) ;;
	esac
done 
