#!/bin/bash
# Delete minion port and transtition to V-Dn
export MPORT=vxlan0
export MPORT_ID=21
export IPSEC_ADAPTER=eth2 
export REMOTE_IPSEC_ADDR=192.100.88.10

export MINION_STATUS=/var/minion/service
export PORT_STATUS=`dirname $MINION_STATUS`/ports/$MPORT
# Check minions state to delete minion port
cat $PORT_STATUS | grep "V-Up"
if [[ $? != 0  ]]; then
 echo "Port not in correct state for delete operation."
 exit
fi

# remove minion port from ovs-bridge
ovs-vsctl --if-exists del-port ovs-br1 $MPORT

# turn off link
ip link set down $MPORT

# delete vxlan adapter from forwarding table
bridge fdb del 00:00:00:00:00:00 dst $REMOTE_IPSEC_ADDR dev $MPORT

# remove vxlan adapter
ip link delete $MPORT 

# transition state to V-Dn for the port status

echo "V-DX VXlan adapter deleted" > $PORT_STATUS
# If all ports are down, transition minion service to V-Dn as well.:w


echo "I-TO IPsec Tunnel Open" > $MINION_STATUS
